#include "pch.h"

tTransform g_Trans = {};

extern const char* ASSET_TYPE_STR[(UINT)ASSET_END] =
{
	"MESH",
	"MESHDATA",
	"PREFAB",
	"MATERIAL",
	"GRAPHICSHADER",
	"COMPUTESHADER",
	"LEVEL",
	"TEXTURE",
	"SOUND",
	"SPRITE",
	"FLIPBOOK",
};

extern const wchar_t* ASSET_TYPE_WSTR[(UINT)ASSET_END] =
{
	L"MESH",
	L"MESHDATA",
	L"PREFAB",
	L"MATERIAL",
	L"GRAPHICSHADER",
	L"COMPUTESHADER",
	L"LEVEL",
	L"TEXTURE",
	L"SOUND",
	L"SPRITE",
	L"FLIPBOOK",
};

extern const char* COMPONENT_TYPE_STR[(UINT)COMPONENT_TYPE::END] =
{
	"TRANSFORM",
	"CAMERA",
	"COLLIDER2D",
	"COLLIDER3D",
	"LIGHT2D",
	"LIGHT3D",
	"MESHRENDER",
	"SPRITE_RENDER",
	"FLIPBOOK_RENDER",
	"TILE_RENDER",
	"PRATICLE_RENDER",
	"SKYBOX",
	"DECAL",
	"LANDSCAP",
};

extern const wchar_t* COMPONENT_TYPE_WSTR[(UINT)COMPONENT_TYPE::END] =
{
	L"TRANSFORM",
	L"CAMERA",
	L"COLLIDER2D",
	L"COLLIDER3D",
	L"LIGHT2D",
	L"LIGHT3D",
	L"MESHRENDER",
	L"SPRITE_RENDER",
	L"FLIPBOOK_RENDER",
	L"TILE_RENDER",
	L"PRATICLE_RENDER",
	L"SKYBOX",
	L"DECAL",
	L"LANDSCAP",
};